# -*- coding: utf-8 -*-
"""mushrooms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QIN1_1mlOTf_5_YVN3UutsaEkuPdfGM9

# **import library**
"""

import pickle
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
np.random.seed(42)

"""# **load data**"""

#load data
load_data=pd.read_csv(r"/content/mushrooms.csv")

"""#view sample data"""

#print(load_data.head())

"""# **handel missing data**"""

#print(load_data.info())
#print(load_data.isna())

"""# ** map labled data **"""

X=load_data.drop('class',axis=1)
y=load_data['class']

"""# **convert letters to numbers**"""

Encoder_x=LabelEncoder()
for col in X.columns:
    X[col]=Encoder_x.fit_transform(X[col])
Encoder_y=LabelEncoder()
y=Encoder_y.fit_transform(y)

"""#**split data to train \ test**"""

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

"""#**choose model**"""

model=svm.SVC(C=1, gamma= 0.1, kernel='rbf')

"""#**train model**"""

model.fit(x_train,y_train)

"""# **tune model parms**

from sklearn.model_selection import GridSearchCV
prams={"kernel":("linear","rbf"), "C":[1,5,10], "gamma":[1,0.1,0.01,0.001]}
grid=GridSearchCV(svm.SVC(),prams,verbose=3)
grid.fit(x_train,y_train)
"""

#print(grid.best_params_)
#print(grid.best_score_)

"""# **validate modle**"""

print(model.score(x_train , y_train))
print(model.score(x_test , y_test))

"""#**save model**"""

pickle.dump(model , open(r"mushrooms.pkl","wb"))